# YAML file for experiments
# Current setup has _no_ penalization for hitting walls
exp_id: 1

results_path: './Results/Experiments/Pinball/Fourier'

experiment: rlpy.Experiments.Experiment

# domain: rlpy.Domains.Pinball

domain: rlpy.Domains.PST
domain_params:
    NUM_UAV: 5
#     goalArray:
#         - [0.8, 0.1]
#         - [0.9, 0.2]
#         - [0.9, 0.4]
#     noise: 0.1

representation: rlpy.Representations.RBF
representation_params:
    num_rbfs: 1000
    resolution_max: 25
    resolution_min: 25
    const_feature: False
    normalize: True
    seed: 1


policy: rlpy.Policies.eGreedy
policy_params:
    # representation: also implicit
    epsilon: 0.2

agent: rlpy.Agents.Q_Learning
agent_params:
    # - representation
    # - policy
    # - discount factor = domain.discount_factor = 0.9
    initial_learn_rate: 0.1
    lambda_: 0.9
    learn_rate_decay_mode: 'boyan'
    boyan_N0: 238

checks_per_policy: 5
max_steps: 150000
num_policy_checks: 5
